name: GARM PostgreSQL PoC test

on:
  workflow_dispatch:

jobs:
  test-garm-runner:
    runs-on: garm-poc-pg
    steps:
      - name: Verify runner
        run: |
          echo "Runner is live!"
          echo "Hostname: $(hostname)"
          echo "Date: $(date)"
